const express= require("express")
const auth = require("../controller/auth")
const banquet = require("../controller/banquet/banquet")
const book = require("../controller/book/book")
const cart = require("../controller/cart/cart")
const dish = require("../controller/dish/dish")
const forgot_password = require("../controller/forgot-password")
const login = require("../controller/login")
const menu = require("../controller/menu/menu")
const order = require("../controller/order/order")
const recover_password = require("../controller/recover_password")
const reset_password = require("../controller/reset-password")
const signup = require("../controller/signup")
const staff = require("../controller/staff/staff")
const user = require("../controller/user")
const user2 = require("../controller/user/user")
const verify_mail = require("../controller/verify_email")
const router= express.Router()


router.post("/login", login)
router.post("/signup", signup)
router.post("/verify", verify_mail)
router.get("/", auth)
router.post("/forgot-password", forgot_password)
router.post("/recover-password", recover_password)
router.post("/reset-password", reset_password)
router.post("/api/user/update", user.update)
router.get("/order", order.get)
router.get("/menu/dish", menu.get)
router.get("/api/v1/dish", dish.getDetail)
router.get("/api/v1/banquet-hall/get", banquet.get)
router.post("/api/v3/banquet-hall/add", banquet.add)
router.get("/api/v1/banquet-hall/get/detail", banquet.getDetail)
router.get("/api/v2/staff/get/detail", staff.getDetail)
router.post("/api/v2/staff/get/update", staff.update)
router.get("/api/v3/user/get", user2.getAll)
router.post("/api/v3/user/update", user2.update)
router.post("/api/v3/user/delete", user2.delete)
router.post("/api/v3/banquet-hall/update", banquet.update)
router.post("/api/v1/book/banquet-hall", book.bookBanquetHall)
router.get("/api/v1/user/cart", cart.get)
router.post("/api/v1/book/dish", book.bookDish)
router.post("/api/v1/book/menu", book.bookMenu)

module.exports= router